// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XPqwoTxINpiHr3l1NQ5ZRfB-GKNWzqg',
    appId: '1:376205867149:web:22b8ee55ca317f5e9c8ac4',
    messagingSenderId: '376205867149',
    projectId: 'xploreg-209e1',
    authDomain: 'xploreg-209e1.firebaseapp.com',
    storageBucket: 'xploreg-209e1.appspot.com',
    measurementId: 'G-P3R0CWWWTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7HAO3hqXFA7PFJYf-pYpGjH7HV5UTNqc',
    appId: '1:376205867149:android:cf5dae92a57895099c8ac4',
    messagingSenderId: '376205867149',
    projectId: 'xploreg-209e1',
    storageBucket: 'xploreg-209e1.appspot.com',
  );
}
